options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - node
        name: Node.js build
        image: node:11.13.0
        script:
          - node -v
          - npm install
          - npm test
    - step:
        name: Docker image build
        image: atlassian/pipelines-awscli:1.16.98
        script:
          - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
          - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
          - docker build -t ${AWS_REGISTRY_URL}:$BUILD_ID .
          - docker push ${AWS_REGISTRY_URL}:$BUILD_ID
          - docker tag ${AWS_REGISTRY_URL}:$BUILD_ID ${AWS_REGISTRY_URL}:development
          - docker push ${AWS_REGISTRY_URL}:development
    - step:
        name: Deploy to k8s dev
        image: atlassian/pipelines-kubectl
        deployment: test
        script:
          - kubectl version --client
          - echo $KUBE_TOKEN | base64 -d > kube_token
          - echo $KUBE_CA | base64 -d > ca.pem
          - kubectl config set-cluster k8s-dev --server=https://CB0612D96CF05F7F8DE07661F562BAF7.sk1.eu-west-1.eks.amazonaws.com --certificate-authority=ca.pem
          - kubectl config set-credentials bitbucket-pipeline --token="$(cat kube_token)"
          - kubectl config set-context k8s-dev-context --cluster=k8s-dev --user=bitbucket-pipeline
          - kubectl config use-context k8s-dev-context
          - kubectl set image deployment/nodejs-example nodejs-example=665901990640.dkr.ecr.eu-west-1.amazonaws.com/k8s-node-helloworld:$BITBUCKET_COMMIT
    - step:
        name: Deploy to k8s staging
        image: atlassian/pipelines-kubectl
        deployment: staging
        trigger: manual
        script:
          - kubectl version --client
    - step:
        name: Deploy to k8s production
        image: atlassian/pipelines-kubectl
        deployment: production
        trigger: manual
        script:
          - kubectl version --client